server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**
        filters:
        - RewritePath=/order/(?<path>.*), /$\{path}
      - id: client-service
        uri: lb://client-service
        predicates:
        - Path=/client/**
        filters:
        - RewritePath=/client/(?<path>.*), /$\{path}
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:3000"
              allowedMethods:
              - GET