server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/