server:
  port: ${PORT:8083}

spring:
  application:
    name: search-service
  data:
    rest:
      basePath: /
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8084}/eureka/
