server:
  port: 8082

spring:
  application:
    name: @project.name@
  data:
    rest:
      base-path: /v1
    mongodb:
      port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG